# Generated by Django 2.2.8 on 2021-05-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowrywise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='uuid',
        ),
    ]
